# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0282357eb9f87da80ea5c59c99e5e198043be02ac126d95f5535f964884b9874fade9dcdba8a2795406194637a4f0f71e7609d7679b1f5e1d05f411c5a242de1

test:
  secret_key_base: ffbf62bd89e4f464c99c3391f1b25ee8b16ecd73015c98087e95ec5139a828c95636ea8e8d24f127101533b6d614af412fd190fdaf643a3116c95f7d233e38a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
